//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 02:02:17 PM MSK 
//


package com.severtrans.notification.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Уведомление о подтверждении отгрузки
 * 
 * <p>Java class for DeliveryNotif complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryNotif">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.severtrans.com}Notification">
 *       &lt;sequence>
 *         &lt;element name="line" type="{http://www.severtrans.com}NotificationLine" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryNotif", propOrder = {
    "rest"
})
public class DeliveryNotif
    extends Notification
{

    @XmlElementRef(name = "line", namespace = "http://www.severtrans.com", type = JAXBElement.class, required = false)
    protected List<JAXBElement<NotificationLine>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Line" is used by two different parts of a schema. See: 
     * line 382 of file:/C:/app/notification/notification/src/main/resources/xml/severtrans.xsd
     * line 189 of file:/C:/app/notification/notification/src/main/resources/xml/severtrans.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NotificationLine }{@code >}
     * 
     * 
     */
    public List<JAXBElement<NotificationLine>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<NotificationLine>>();
        }
        return this.rest;
    }

}
