//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.11 at 07:49:23 AM MSK 
//


package com.severtrans.notification.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Shell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Shell">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="skuList" type="{http://www.severtrans.com}ListSKU" minOccurs="0"/>
 *         &lt;element name="partStockRq" type="{http://www.severtrans.com}PartStockRq" minOccurs="0"/>
 *         &lt;element name="partStockRs" type="{http://www.severtrans.com}PartStockRs" minOccurs="0"/>
 *         &lt;element name="order" type="{http://www.severtrans.com}Order" minOccurs="0"/>
 *         &lt;element name="pickOrder" type="{http://www.severtrans.com}PickNotif" minOccurs="0"/>
 *         &lt;element name="shipmentNotif" type="{http://www.severtrans.com}ShipmentNotif" minOccurs="0"/>
 *         &lt;element name="deliveryNotif" type="{http://www.severtrans.com}DeliveryNotif" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shell", propOrder = {
    "customerID",
    "skuList",
    "partStockRq",
    "partStockRs",
    "order",
    "pickOrder",
    "shipmentNotif",
    "deliveryNotif"
})
public class Shell {

    protected Integer customerID;
    protected ListSKU skuList;
    protected PartStockRq partStockRq;
    protected PartStockRs partStockRs;
    protected Order order;
    protected PickNotif pickOrder;
    protected ShipmentNotif shipmentNotif;
    protected DeliveryNotif deliveryNotif;

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCustomerID(Integer value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the skuList property.
     * 
     * @return
     *     possible object is
     *     {@link ListSKU }
     *     
     */
    public ListSKU getSkuList() {
        return skuList;
    }

    /**
     * Sets the value of the skuList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListSKU }
     *     
     */
    public void setSkuList(ListSKU value) {
        this.skuList = value;
    }

    /**
     * Gets the value of the partStockRq property.
     * 
     * @return
     *     possible object is
     *     {@link PartStockRq }
     *     
     */
    public PartStockRq getPartStockRq() {
        return partStockRq;
    }

    /**
     * Sets the value of the partStockRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartStockRq }
     *     
     */
    public void setPartStockRq(PartStockRq value) {
        this.partStockRq = value;
    }

    /**
     * Gets the value of the partStockRs property.
     * 
     * @return
     *     possible object is
     *     {@link PartStockRs }
     *     
     */
    public PartStockRs getPartStockRs() {
        return partStockRs;
    }

    /**
     * Sets the value of the partStockRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartStockRs }
     *     
     */
    public void setPartStockRs(PartStockRs value) {
        this.partStockRs = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the pickOrder property.
     * 
     * @return
     *     possible object is
     *     {@link PickNotif }
     *     
     */
    public PickNotif getPickOrder() {
        return pickOrder;
    }

    /**
     * Sets the value of the pickOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickNotif }
     *     
     */
    public void setPickOrder(PickNotif value) {
        this.pickOrder = value;
    }

    /**
     * Gets the value of the shipmentNotif property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentNotif }
     *     
     */
    public ShipmentNotif getShipmentNotif() {
        return shipmentNotif;
    }

    /**
     * Sets the value of the shipmentNotif property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentNotif }
     *     
     */
    public void setShipmentNotif(ShipmentNotif value) {
        this.shipmentNotif = value;
    }

    /**
     * Gets the value of the deliveryNotif property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryNotif }
     *     
     */
    public DeliveryNotif getDeliveryNotif() {
        return deliveryNotif;
    }

    /**
     * Sets the value of the deliveryNotif property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryNotif }
     *     
     */
    public void setDeliveryNotif(DeliveryNotif value) {
        this.deliveryNotif = value;
    }

}
